"use client";
import "./globals.css";
import { store } from "./store/store";
import { Provider } from "react-redux";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body
          style={{
            minHeight: "100vh",
            maxHeight: "fit-content",
            boxSizing: "border-box",
            backgroundColor: "#f2f5fd",
          }}
        >
          {children}
        </body>
      </Provider>
    </html>
  );
}
